reload:
  description: Reload localtuya and reconnect to all devices.

set_dp:
  description: Change the value of a datapoint (DP)
  fields:
    device_id:
      description: Device ID of device to change datapoint value for
      example: 11100118278aab4de001
    dp:
      description: Datapoint index
      example: 1
    value:
      description: New value to set
      example: False

send_command:
  description: Send a command to a device
  fields:
    device_id:
      description: Device ID of device to send command to
      example: 11100118278aab4de001
    value:
      description: Command JSON
      example: >
        {
          "code": "manual_feed",
          "value": 1
        }
